#!/usr/bin/perl
use Net::LDAP;
use Digest::SHA;
use MIME::Base64;

if (!defined $ARGV[0]){die "No input file!\n"; }
if (!open OUTPUT_LDIF, ">", $ARGV[0]) { die "Cannot open file: $ARGV[0]\n"; }


###################
# Bind to ronTest #
###################

#Obtain uidIdentifierUPLB
$ldap_server_ip_and_port = "10.0.100.201:389";
$ldap = Net::LDAP->new( $ldap_server_ip_and_port ) or die "Could not connect to LDAP Server!";
print "Enter bind DN Password: ";
# Code non-portable (UNIX/Linux only)
	system('stty','-echo');
	chop($password=<STDIN>);
	system('stty','echo');
# End non-portable

$mesg = $ldap->bind( "cn=admin,dc=uplb,dc=edu,dc=ph", password => $password );
if ($mesg->code){ die "Fatal Error: Authentication Fail\n"; }
#Retrieve uidLatestNumber

#Retrieve gidGroups
 $mesg = $ldap->search(
                base   => "ou=people,dc=uplb,dc=edu,dc=ph",
                filter => "(cn=*)",
                attrs  => "uidNumber"
              );
foreach $entry ($mesg->entries){
        my $identifier = $entry->get_value("uidNUmber");
		say OUTPUT_LDIF "dn: uniqueIdentifierUPLB=$identifier,ou=people,dc=uplb,dc=edu,dc=ph";
		say OUTPUT_LDIF "changetype: delete";
		say OUTPUT_LDIF;
}

say OUTPUT_LDIF "dn: cn=uidLatestNumber,ou=numberHolder,dc=uplb,dc=edu,dc=ph";
say OUTPUT_LDIF "changetype: modify";
say OUTPUT_LDIF "replace: serialNumber";
say OUTPUT_LDIF "serialNumber: 0";

$ldap->unbind;
close OUTPUT_LDIF;

$intoLDAP = `ldapmodify -h 10.0.100.201 -p 389 -D "cn=admin,dc=uplb,dc=edu,dc=ph" -w testtesttest -f delete.ldif`;